language: node_js
_aliases:
  - &node-prod
    # This is the NodeJS version we run in production.
    node_js: '10'
  - &node-next
    # This is the next NodeJS version we will support.
    node_js: '11'

cache:
  yarn: true

# See: https://github.com/mozilla/addons-frontend/issues/3034
install: yarn install --pure-lockfile

matrix:
  fast_finish: true

jobs:
  include:
    - name: unit tests (node@production)
      <<: *node-prod
      script: yarn test-ci
    - name: unit tests (node@next)
      <<: *node-next
      script: yarn test
      # Make sure we can build a production bundle.
      # This also does type checking.
    - name: build (node@production)
      <<: *node-prod
      script: yarn build
      # This is a workaround for how `build` does not type check test files.
      # See https://github.com/mozilla/addons-code-manager/issues/33
    - name: type checking (node@production)
      <<: *node-prod
      script: yarn typecheck
    - name: type coverage (node@production)
      <<: *node-prod
      script: yarn type-coverage
    - name: prettier
      <<: *node-prod
      script: yarn prettier-ci
    - name: linter (node@production)
      <<: *node-prod
      script: yarn lint
