language: node_js
_aliases:
  - &node-prod
    # This is the NodeJS version we run in production.
    node_js: '10'
  - &node-next
    # This is the next NodeJS version we will support.
    node_js: '12'

cache:
  yarn: true

# See: https://github.com/mozilla/addons-frontend/issues/3034
install: yarn install --pure-lockfile

jobs:
  fast_finish: true
  include:
    - name: unit tests (node@production)
      <<: *node-prod
      script: yarn test-ci
    - name: unit tests (node@next)
      <<: *node-next
      script: yarn test
      # Make sure we can build a production bundle.
      # This also does type checking.
    - name: build (node@production)
      <<: *node-prod
      script: yarn build
      # This is a workaround for how `build` does not type check test files.
      # See https://github.com/mozilla/addons-code-manager/issues/33
    - name: type checking (node@production)
      <<: *node-prod
      script: yarn typecheck
    - name: type coverage (node@production)
      <<: *node-prod
      script: yarn type-coverage
    - name: prettier
      <<: *node-prod
      script: yarn prettier-ci
    - name: linter (node@production)
      <<: *node-prod
      script: yarn lint
    - name: storybook-smoke-test (node@production)
      <<: *node-prod
      script: yarn storybook-smoke-test
    - name: yarn serve (node@production)
      <<: *node-prod
      script:
        - yarn build
        - yarn serve &
        - sleep 30 && kill $! # kill last backgrounded process (a.k.a. the node server)
    - stage: storybook deployment
      <<: *node-prod
      if: branch = master AND type = push AND fork = false
      script: echo "Deploying to GitHub Pages..."
      after_success: yarn storybook-deploy --ci

notifications:
  slack:
    if: branch = master
    on_success: change
    on_failure: always
    secure: hitY014qRG17K1ewh797AsAZBw50RC3BaI+3B8tDJKJL7f9osBl/yqCux+VBvCC7GdU7zDB5MZAPcTNtqtBO0gkEVUCIF/FSanX/75HMvJPcQqq+nq0M/KgZW2wdjGJf6g+Q7rNDOa3al+6X3mw1xBLx8tUac7+u0klWmP/Ev4VO+BXQO/vcAJA7Qappj7oynP55UsTPNDfc1gF4d/cL9+7K2QFzzo2N5ak7xZ4zlxw1nNZNZfBdjbKu1PIhgZw2zHU4uLnVdDZYnBXUB9VMFi/a4xvUwPL/ZE5wOz9vvWMsjTGz6YIqm0/3VpHeN+75c8qvZpLt04H8lqrOraukj4vGQBfYo7/JZehn2WTjn9P7xmlR7IARFHPfKBuEgxFE6IkJ54QKy3fN/KNDpOlg8ZqhoLQeL6bJsA0LYWs5t0Hd8QthgBuZPHK2FLFvan9TcUjQ+9N7oCpawEXloTO9Ubj+CAEMnNVnrPslLSzgrFWIN19gO/+oVR+AQRDE57PPQKZ99LpsmzJJyg1PXHwlhd/UGD47cjdnqIuS7tRqtW3tclSndaT8k1SQRXQjEmOBeQVGC+JXhOrKbEt0cMBjb0+CK8hiIWadV7a5uQB7FEDWPggAsnjBgPrSEGbN2k+NVhlQTH2k36jbrROoj2MM5WjRw2Zn+j52QiG/STtmal0=
