version: '3'
services:
  web:
    build: .
    env_file:
      - .env.dev
      - .env.common-local
    environment:
      # FxA `local` config redirects to `localhost:3000`
      - PORT=3000
    ports:
     - "3000:3000"
